### ISSUE TITLE
trying to understand code style

### ISSUE THREAD

**Issue by tjwebb** [CartoDB/node-redis-mpool#6]
see: https://github.com/CartoDB/node-redis-mpool/blob/master/test/redis_pool.test.js#L31-L37

I don't understand why there is a loop and a done callback and all that. You could simply write 

```
assert(typeof redis_pool.acquire === 'function')
```

Am I missing something? I had to refactor this test because it breaks on node 6.x for some reason.

**Comment by rochoa** [comment]
Maybe @strk could help here 😄 .

BTW, it should work with Node.js 6.x now.

**Comment by strk** [comment]
no reason for that loop to be simpler, but would be interesting to know why it breaks with new node version
